
# Core System
exec-once = waybar
exec-once = hyprpaper
exec-once = dunst
exec-once = clipse -listen
exec-once = tmux new-session -d -s main
exec-once = systemctl --user start hyprpolkitagent
exec-once = darkman run

# System Utilities
exec-once = blueman-applet
exec-once = nm-applet
exec-once = systemctl --user start opentabletdriver
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Terminal Sessions
exec-once = [workspace special:terminal silent] kitty -e tmux new-session -t main -s main-$(date +%s)

# Wapaper
exec-once = .config/hypr/randomize-wp.sh

# Applications
# exec-once = chromium
exec-once = [workspace 1 silent] zen-browser
# exec-once = [workspace 6 silent] steam

# Communication
exec-once = [workspace special:magic silent] Telegram
# exec-once = [workspace special:magic silent] Technogram
exec-once = [workspace special:magic silent] equibop

# UwU
# exec-once = online-status-client

